# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import makler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buero', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Energieausweis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baujahr', models.IntegerField(default=0)),
                ('heizungsart', models.CharField(default='Fernwärme', max_length=250)),
                ('befeuerungEnergietraeger', models.CharField(default='Pelletheizung', max_length=500)),
                ('energiekennwert', models.IntegerField(default=0)),
                ('effiziensklasse', models.CharField(default='B', max_length=10)),
                ('ausweisdatum', models.DateField(default=django.utils.timezone.now)),
                ('gueltigBis', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImmoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('livingSpace', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groundSpace', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pricePerQuadratMeter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_apartment', models.BooleanField()),
                ('is_house', models.BooleanField()),
                ('is_sold', models.BooleanField()),
                ('pic1', models.ImageField(default='images/index.jpeg', upload_to=makler.models.image_upload_path)),
                ('pic2', models.ImageField(default='images/index.jpeg', upload_to=makler.models.image_upload_path)),
                ('pic3', models.ImageField(default='images/index.jpeg', upload_to=makler.models.image_upload_path)),
                ('pic4', models.ImageField(default='images/index.jpeg', upload_to=makler.models.image_upload_path)),
                ('pic5', models.ImageField(default='images/index.jpeg', upload_to=makler.models.image_upload_path)),
                ('pic6', models.ImageField(default='images/index.jpeg', upload_to=makler.models.image_upload_path)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='energieausweis',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makler.Realestate'),
        ),
    ]
