# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energieausweis',
            old_name='name',
            new_name='name_objekt',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='name',
            new_name='name_objekt',
        ),
    ]
