# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0002_auto_20170115_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energieausweis',
            name='name_objekt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='name_objekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makler.Energieausweis'),
        ),
    ]
