# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0003_auto_20170115_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='energieAusweis',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='makler.Energieausweis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestate',
            name='name_objekt',
            field=models.CharField(max_length=200),
        ),
    ]
