# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0004_auto_20170115_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='energieausweis',
            name='addresse',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
