# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0005_energieausweis_addresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='immonews',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='makler.Realestate'),
            preserve_default=False,
        ),
    ]
