# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0007_remove_immonews_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='name_objekt',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='energieAusweis',
        ),
    ]
