# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0009_auto_20170116_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energieausweis',
            old_name='name_objekt',
            new_name='name',
        ),
    ]
