# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0011_auto_20170117_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energieausweis',
            name='addresse',
        ),
        migrations.RemoveField(
            model_name='energieausweis',
            name='name',
        ),
    ]
