# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0012_auto_20170117_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='energieAusweis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.PassEnergie'),
        ),
    ]
