# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20170117_1111'),
        ('makler', '0014_delete_energieausweis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='energieAusweis',
        ),
        migrations.AddField(
            model_name='realestate',
            name='energieAusweis',
            field=models.ManyToManyField(to='extras.PassEnergie'),
        ),
    ]
