# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_images'),
        ('makler', '0015_auto_20170121_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='pic6',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='pic1',
        ),
        migrations.AddField(
            model_name='realestate',
            name='pic1',
            field=models.ManyToManyField(to='extras.Images'),
        ),
    ]
