# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_images'),
        ('makler', '0016_auto_20170122_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='energieAusweis',
        ),
        migrations.AddField(
            model_name='realestate',
            name='energieAusweis',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='extras.PassEnergie'),
            preserve_default=False,
        ),
    ]
