# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_images_name'),
        ('makler', '0018_auto_20170122_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='bild',
        ),
        migrations.AddField(
            model_name='realestate',
            name='bild',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='extras.Images'),
            preserve_default=False,
        ),
    ]
