# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_images_name'),
        ('makler', '0021_auto_20170123_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='bild',
        ),
        migrations.AddField(
            model_name='realestate',
            name='bild',
            field=models.ManyToManyField(to='extras.Images'),
        ),
    ]
