# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import makler.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_images_name'),
        ('makler', '0022_auto_20170123_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einfamilien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verkauft', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('objektart', models.CharField(max_length=200)),
                ('lage', models.CharField(max_length=200)),
                ('baujahr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('grundstücksfl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('wohnfl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('gewerbefl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('nutzfl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('mieteinnhmSoll', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('mieteinnhmIst', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('leerstand', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('kfpreis', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('faktor', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('honorar', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('etagen', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('anzahlZi', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('hausgld', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('lfzMietVertrg', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('bild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.Images')),
                ('energieAusweis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.PassEnergie')),
            ],
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='bild',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='energieAusweis',
        ),
        migrations.AddField(
            model_name='contact',
            name='addresse',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='bild',
            field=models.ImageField(blank=True, upload_to=makler.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='contact',
            name='mail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Realestate',
        ),
    ]
