# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0023_auto_20170123_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Einfamilien',
            new_name='Immobilie',
        ),
    ]
