# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import makler.models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0026_auto_20170123_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leistungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('PE', 'Person'), ('VK', 'Verkaufen'), ('AK', 'Ankaufen'), ('BW', 'Bewertung'), ('BR', 'Beratung')], max_length=2)),
                ('bild', models.ImageField(blank=True, upload_to=makler.models.image_upload_path)),
                ('text', models.TextField()),
            ],
        ),
    ]
