# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0027_leistungen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilie',
            name='bild',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Images'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='energieAusweis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='extras.PassEnergie'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='grdriss',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Grundriss'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='objekbesrbng',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Beschreibung'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Video'),
        ),
    ]
