# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0029_auto_20170124_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilie',
            name='mieteinnhmIst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
