# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import makler.models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0030_auto_20170124_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immonews',
            name='content',
        ),
        migrations.AddField(
            model_name='immonews',
            name='bild',
            field=models.ImageField(blank=True, upload_to=makler.models.image_upload_path_news),
        ),
        migrations.AddField(
            model_name='immonews',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='immonews',
            name='linkname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='immonews',
            name='obererText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='immonews',
            name='untererText',
            field=models.TextField(blank=True),
        ),
    ]
