# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0031_auto_20170124_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilie',
            name='baujahr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
