# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0032_auto_20170124_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilie',
            name='euroQuadratM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
