# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import makler.models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0033_immobilie_euroquadratm'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='obererText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='untererText',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='bild',
            field=models.ImageField(blank=True, upload_to=makler.models.image_upload_path_news),
        ),
    ]
