# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0034_auto_20170124_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilie',
            name='anzahlZi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='baujahr',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='etagen',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='euroQuadratM',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='faktor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='gewerbefl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='grundstücksfl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='hausgld',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='honorar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='kfpreis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='leerstand',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='mieteinnhmIst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='mieteinnhmSoll',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='nutzfl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='wohnfl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
