# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0035_auto_20170125_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilie',
            name='lfzMietVertrg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
    ]
