# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0038_auto_20170126_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilie',
            name='lfzMietVertrg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
    ]
