# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0040_auto_20170126_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilie',
            name='bild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Images'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='energieAusweis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extras.PassEnergie'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='grdriss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Grundriss'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='objekbesrbng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Beschreibung'),
        ),
        migrations.AlterField(
            model_name='immobilie',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extras.Video'),
        ),
    ]
