# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassEnergie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baujahr', models.IntegerField(default=0)),
                ('heizungsart', models.CharField(default='Fernwärme', max_length=250)),
                ('befeuerungEnergietraeger', models.CharField(default='Pelletheizung', max_length=500)),
                ('energiekennwert', models.IntegerField(default=0)),
                ('effiziensklasse', models.CharField(default='B', max_length=10)),
                ('ausweisdatum', models.DateField(default=django.utils.timezone.now)),
                ('gueltigBis', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
