# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=200)),
                ('bild', models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path)),
            ],
        ),
    ]
