# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Energieausweis',
            new_name='PassEnergie',
        ),
    ]
