# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20170117_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path)),
            ],
        ),
    ]
