# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_images_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beschreibung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objektbeschr', models.TextField()),
                ('lage', models.TextField()),
                ('Ausstattung', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='images',
            name='image4',
            field=models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='images',
            name='image5',
            field=models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='images',
            name='image6',
            field=models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='images',
            name='image7',
            field=models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='images',
            name='image8',
            field=models.ImageField(default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
    ]
