# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenergie',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
