# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_passenergie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beschreibung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objektbeschr', models.TextField()),
                ('lage', models.TextField()),
                ('ausstattung', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grundriss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grdriss1', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('grdriss2', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('grdriss3', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='images/index.jpeg', upload_to=extras.models.image_upload_path)),
                ('image2', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('image3', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('image4', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('image5', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('image6', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('image7', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('image8', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to=extras.models.image_upload_path)),
            ],
        ),
    ]
