# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_auto_20170123_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grundriss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grdriss1', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('grdriss2', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
                ('grdriss3', models.ImageField(blank=True, upload_to=extras.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to=extras.models.image_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='image1',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image2',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image3',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image4',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image5',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image6',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image7',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image8',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
    ]
