# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0006_auto_20170123_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grundriss',
            name='grdriss1',
            field=models.ImageField(blank=True, default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image1',
            field=models.ImageField(blank=True, default='images/index.jpeg', upload_to=extras.models.image_upload_path),
        ),
    ]
