# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0006_beschreibung_grundriss_images_video'),
        ('makler', '0029_auto_20170124_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='passenergie',
            name='name',
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='ausweisdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='baujahr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='befeuerungEnergietraeger',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='effiziensklasse',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='energiekennwert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='gueltigBis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='heizungsart',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
