# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_auto_20170124_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grundriss',
            name='grdriss1',
            field=models.ImageField(blank=True, upload_to=extras.models.image_upload_path),
        ),
    ]
