# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_auto_20170124_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
