# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0008_auto_20170124_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenergie',
            name='ausweisdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='baujahr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='befeuerungEnergietraeger',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='effiziensklasse',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='energiekennwert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='gueltigBis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenergie',
            name='heizungsart',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
