# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0009_auto_20170124_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beschreibung',
            old_name='Ausstattung',
            new_name='ausstattung',
        ),
    ]
