# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0010_auto_20170124_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='grundriss',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
