# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 20:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0010_auto_20170126_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beschreibung',
            name='ausstattung',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beschreibung',
            name='lage',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='beschreibung',
            name='objektbeschr',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
