# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0011_auto_20170212_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beschreibung',
            name='ausstattung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beschreibung',
            name='lage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beschreibung',
            name='objektbeschr',
            field=models.TextField(),
        ),
    ]
