# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0011_auto_20170124_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grundriss',
            name='name',
            field=models.CharField(default='grundriss', max_length=250),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(default='image', max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='video', max_length=250),
        ),
    ]
