# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0012_auto_20170124_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='video', max_length=250)),
                ('expose', models.FileField(blank=True, upload_to=extras.models.pdf_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
