# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0013_auto_20170126_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expose',
            name='name',
            field=models.CharField(default='pdf', max_length=250),
        ),
    ]
