# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0013_auto_20170212_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beschreibung',
            name='objektbeschr',
            field=models.TextField(),
        ),
    ]
