# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0015_auto_20170214_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='beschreibung',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expose',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grundriss',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='images',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
